# Generated by Django 2.1 on 2019-06-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_owners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
    ]
